---
title: "Geospatial analysis"
---

As you can guess, this part is still a work in progress. Check
back winter quarter, 2027 to see our progress

We are still discussing what tool to emphasize. Will we leave ArcGIS Online
behind for part 3 of the series?

Will we move to the Free and Open Source QGIS?

Stay tuned to find out!

## AGO layers vs. local layers

Keeping track of where the data underlying layers is located is challenging even for advanced geospatial analysts. 

– Will this session turn out to be very much a ‘where are my files’ reinforcement like we try to make the Unix Shell?

## Flavors of data analysis: 

- buffering
- interpolation
- zonal statistics
- raster calculation

### Raster calculations

Example analysis: from workshop 2, how did that slope layer get made?
With a raster calculation.

### Buffering
Example analysis: maybe your friend is really afraid of heights, and wants to make sure that the route doesn't include super steep drop offs. 

1. buffer 30 meters around the streets
1. There's a chance to teach about credits here. The buffer costs 2.x credits.
1. gotcha: layers much have unique names across the organization.
So use your initials in this step. `sb_jj_roads_buffer`
1. Find clusters of large values in the pixels that lay underneath the buffer.
1. highlight any intersection with areas where there are large numbers of very steep pixels nearby.
1. Cutting a raster to a mask is called `nibbling`


### another
Which parts of campus are least served by the bike path network?


Potential simple analysis as end product  (this section should be moved to 3) 
- Zonal statistics 
- Count number of points within a polygon 
- Heatmap from points 
- Buffering


